# Generated by Django 4.0.1 on 2022-02-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_field',
            field=models.TextField(max_length=200, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
