# Generated by Django 4.0.1 on 2022-02-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('change_user_in_own_project', 'Change user in own project'),), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('add_task_in_own_project', 'Add tasks in own project'), ('change_task_in_own_project', 'Change tasks in own project'), ('delete_task_in_own_project', 'Delete tasks in own project')), 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
